import { sendToOllama, sendToOllamaNoStream } from '../llm/ollama.js';
import {AGENT_NETWORK_TOOLS_SPECS} from './tools.js'
import {AGENT_FUNCTION_DECLARATIONS, SCENARIOS_AGENT_FUNCTION_DECLARATIONS} from './tools.js'



// Base URL configuration for your local backend network service
const BASE_SERVER_URL = 'http://localhost:3005';

/**
 * Creates a fast O(1) hash map dictionary directly from your specs array
 */
const toolSpecsMap = new Map(
  AGENT_NETWORK_TOOLS_SPECS.map(spec => [spec.name, spec])
);

/**
 * Resolves tool function schemas and dispatches request packets to your backend
 * @param {string} toolName - Name of function returned from LLM (e.g. 'check_availability')
 * @param {Object} args - Arguments generated by LLM text logic
 */
// async function executeDynamicTool(toolName, args) {
//   const spec = toolSpecsMap.get(toolName);
  

//   if (!spec) {
//     throw new Error(`Tool "${toolName}" is not registered in AGENT_NETWORK_TOOLS_SPECS.`);
//   }

//   const targetUrl = `${BASE_SERVER_URL}${spec.endpoint}`;
//   const options = {
//     method: spec.method || 'POST',
//     headers: {
//       'Content-Type': 'application/json'
//     }
//   };

//   // Safe payload builder based on defined HTTP verbs
//   if (options.method === 'GET') {
//     const queryParams = new URLSearchParams(args).toString();
//     return fetch(`${targetUrl}?${queryParams}`, { method: 'GET' }).then(res => res.json());
//   }

//    // POST
//   if (options.method === 'PUT') {
//     // Extract route parameter fields (like id) separate from request body content parameters
//     const { id, ...bodyFields } = args;
    
//     // Construct target URL string substituting the specific resource identifier index if needed
//     const executionUrl = id ? targetUrl.replace(':id', id) : targetUrl;
    
//     return fetch(executionUrl, {
//       method: 'PUT',
//       headers: {
//         'Content-Type': 'application/json'
//       },
//       body: JSON.stringify(bodyFields)
//     }).then(res => res.json());
//   }

//   // POST: Send arguments directly as the main request body JSON object
//   options.body = JSON.stringify(args || {});

//   console.log("request", targetUrl, " ",  " " , options);

//   const response = await fetch(targetUrl, options);
  
//   if (!response.ok) {
//     throw new Error(`Network tool execution failed on ${spec.endpoint}. Status: ${response.status}`);
//   }
// const results = await response.json()
// console.log("results", results);
//   return  results;
// }


async function executeDynamicTool(toolName, args) {
  const spec = toolSpecsMap.get(toolName);

  if (!spec) {
    throw new Error(`Tool "${toolName}" is not registered in AGENT_NETWORK_TOOLS_SPECS.`);
  }

  // 1. Extract path parameter fields ('id') separate from request body content parameters
  const { id, ...cleanedArgs } = args || {};

  // 2. Construct the dynamic URL path, substituting ':id' with the actual resource index value if specified
  let targetUrl = `${BASE_SERVER_URL}${spec.endpoint}`;
  if (id && targetUrl.includes(':id')) {
    targetUrl = targetUrl.replace(':id', encodeURIComponent(id));
  } else if (id && !targetUrl.includes(':id')) {
    // Fallback: If 'id' is supplied but ':id' placeholder isn't in spec, automatically append it
    targetUrl = `${targetUrl}/${encodeURIComponent(id)}`;
  }

  const options = {
    method: spec.method || 'POST',
    headers: {
      'Content-Type': 'application/json'
    }
  };

  // 3. Configure Payload Structures dynamically based on standard HTTP verbs
  if (options.method === 'GET') {
    // Serialize all arguments into standard URL query strings
    const queryParams = new URLSearchParams(cleanedArgs).toString();
    if (queryParams) {
      targetUrl = `${targetUrl}?${queryParams}`;
    }
  } else if (options.method === 'PUT' || options.method === 'POST') {
    // Assign payload elements directly inside the outgoing request body
    options.body = JSON.stringify(cleanedArgs);
  } else if (options.method === 'DELETE') {
    // If the DELETE endpoint accepts additional body configurations, attach them
    if (Object.keys(cleanedArgs).length > 0) {
      options.body = JSON.stringify(cleanedArgs);
    }
  }

  // 4. Centralized Network Tracing & Execution Pipeline
  console.log("Request Trace:", options.method, targetUrl, options.body || '');

  const response = await fetch(targetUrl, options);
  
  if (!response.ok) {
    throw new Error(`Network tool execution failed on ${spec.endpoint}. Status: ${response.status} (${response.statusText})`);
  }

  const results = await response.json();
  console.log("Execution Results:", results);
  
  return results;
}


// Define tools
const weatherTool = {
  type: 'function',
  function: {
    name: 'get_current_weather',
    description: 'Get current weather or temperature for a given city.',
    parameters: {
      type: 'object',
      required: ['city'],
      properties: { city: { type: 'string', description: 'City name' } }
    }
  }
};

const clothingTool = {
  type: 'function',
  function: {
    name: 'get_clothing_advice',
    description: 'Get clothing advice based on conditions.',
    parameters: {
      type: 'object',
      required: ['condition'],
      properties: { condition: { type: 'string', description: 'Weather condition' } }
    }
  }
};
  const messages = [
    {
      role: "system",
      content: `
You are a helpful weather and fashion assistant.
Answer clearly and concisely.
      `
    }
  ];
const toolRegistry = [clothingTool, weatherTool];

// Mock API Call functions
async function mockWeather(city) {
  return { city, temperature: 14, condition: 'Rainy' };
}
async function mockClothing(condition) {
  return { outfit: 'Raincoat and heavy boots', accessories: 'Umbrella' };
}


export async function runAgentLoop(messages, res) {
  const MAX_ITERATIONS = 10;

  try {
    for (let iteration = 0; iteration < MAX_ITERATIONS; iteration++) {
      let toolCalls = [];

      const responseStream = await sendToOllama(
        messages,
        AGENT_FUNCTION_DECLARATIONS
      );

      for await (const chunk of responseStream) {
        // Stream reasoning
        if (chunk.message?.thinking) {
          res.write(
            `event: thinking\ndata: ${JSON.stringify(
              chunk.message.thinking
            )}\n\n`
          );
        }

        // Stream visible response tokens
        if (chunk.message?.content) {
          res.write(
            `event: content\ndata: ${JSON.stringify(
              chunk.message.content
            )}\n\n`
          );
        }

        // Collect ALL tool calls emitted during streaming
        if (chunk.message?.tool_calls?.length) {
          toolCalls.push(...chunk.message.tool_calls);
        }
      }

      // No tool calls -> agent is finished
      if (toolCalls.length === 0) {
        res.write(`event: done\ndata: {}\n\n`);
        res.end();
        return;
      }

      // Save assistant tool request
      messages.push({
        role: "assistant",
        tool_calls: toolCalls
      });

      // Execute tool calls
      const toolMessages = await Promise.all(
        toolCalls.map(async (call) => {
          const toolName = call.function?.name;

          let toolArgs;

          try {
            toolArgs =
              typeof call.function?.arguments === "string"
                ? JSON.parse(call.function.arguments)
                : call.function?.arguments || {};
          } catch {
            toolArgs = {};
          }

          res.write(
            `event: thinking\ndata: ${JSON.stringify(
              `⚡ Running ${toolName}...`
            )}\n\n`
          );

          let toolResult;

          try {
            toolResult = await executeDynamicTool(
              toolName,
              toolArgs
            );
          } catch (error) {
            toolResult = {
              success: false,
              error: error.message
            };
          }

          // Optional: stream result preview
          res.write(
            `event: thinking\ndata: ${JSON.stringify(
              `✓ ${toolName} completed`
            )}\n\n`
          );

          return {
            role: "tool",
            tool_name: toolName,
            tool_call_id: call.id,
            content: JSON.stringify(toolResult)
          };
        })
      );

      messages.push(...toolMessages);
    }

    // Safety cutoff
    res.write(
      `event: error\ndata: ${JSON.stringify(
        "Maximum agent iterations reached."
      )}\n\n`
    );

    res.end();
  } catch (error) {
    console.error("Agent loop error:", error);

    res.write(
      `event: error\ndata: ${JSON.stringify(
        error.message
      )}\n\n`
    );

    res.end();
  }
}

export async function runScenariosAgentLoop(messages, res) {
  const MAX_ITERATIONS = 10;

  console.log("got hereee toooooooooooo")

  try {
    for (let iteration = 0; iteration < MAX_ITERATIONS; iteration++) {
      let toolCalls = [];

      const responseStream = await sendToOllamaNoStream(
        messages,
        SCENARIOS_AGENT_FUNCTION_DECLARATIONS
      );

      for await (const chunk of responseStream) {
        // Stream reasoning
        if (chunk.message?.thinking) {
          res.write(
            `event: thinking\ndata: ${JSON.stringify(
              chunk.message.thinking
            )}\n\n`
          );
        }

        // Stream visible response tokens
        if (chunk.message?.content) {
          res.write(
            `event: content\ndata: ${JSON.stringify(
              chunk.message.content
            )}\n\n`
          );
        }

        // Collect ALL tool calls emitted during streaming
        if (chunk.message?.tool_calls?.length) {
          toolCalls.push(...chunk.message.tool_calls);
        }
      }

      // No tool calls -> agent is finished
      if (toolCalls.length === 0) {
        res.write(`event: done\ndata: {}\n\n`);
        res.end();
        return;
      }

      // Save assistant tool request
      messages.push({
        role: "assistant",
        tool_calls: toolCalls
      });

      // Execute tool calls
      const toolMessages = await Promise.all(
        toolCalls.map(async (call) => {
          const toolName = call.function?.name;

          let toolArgs;

          try {
            toolArgs =
              typeof call.function?.arguments === "string"
                ? JSON.parse(call.function.arguments)
                : call.function?.arguments || {};
          } catch {
            toolArgs = {};
          }

          res.write(
            `event: thinking\ndata: ${JSON.stringify(
              `⚡ Running ${toolName}...`
            )}\n\n`
          );

          let toolResult;

          try {
            toolResult = await executeDynamicTool(
              toolName,
              toolArgs
            );
          } catch (error) {
            toolResult = {
              success: false,
              error: error.message
            };
          }
          console.log(toolName, "///////////")

          // Optional: stream result preview
          res.write(
            `event: thinking\ndata: ${JSON.stringify(
              `✓ ${toolName} completed`
            )}\n\n`
          );

          return {
            role: "tool",
            tool_name: toolName,
            tool_call_id: call.id,
            content: JSON.stringify(toolResult)
          };
        })
      );

      messages.push(...toolMessages);
    }

    // Safety cutoff
    res.write(
      `event: error\ndata: ${JSON.stringify(
        "Maximum agent iterations reached."
      )}\n\n`
    );

    res.end();
  } catch (error) {

    console.error("Agent loop error:", error);

    res.write(
      `event: error\ndata: ${JSON.stringify(
        error.message
      )}\n\n`
    );

    res.end();
  }
}


// export async function runAgentLoop(messages, res) {
//   console.log(messages);
//   // Call lower ollama wrapper
//   const responseStream = await sendToOllama(messages, AGENT_FUNCTION_DECLARATIONS);
//   let toolCalls = null;

//   for await (const chunk of responseStream) {
//     // 1. Immediately stream internal reasoning paths to the frontend
//     if (chunk.message.thinking) {
//       res.write(`event: thinking\ndata: ${JSON.stringify(chunk.message.thinking)}\n\n`);
//     } 
//     // 2. Stream base response content tokens
//     else if (chunk.message.content) {
//       res.write(`event: content\ndata: ${JSON.stringify(chunk.message.content)}\n\n`);
//     }

//     // 3. Keep records of tool intents if model emits them
//     if (chunk.message.tool_calls?.length) {
//       toolCalls = chunk.message.tool_calls;
//     }
//   }

//   // 4. Intercept Tool Call Execution Loops
//   if (toolCalls && toolCalls.length > 0) {
//     // Append assistant tool intent into state array
//     messages.push({ role: 'assistant', tool_calls: toolCalls });

//     for (const call of toolCalls) {
//       let toolResult = null;
//       const toolName = call.function.name;
//       const toolArgs = call.function.arguments;
      
//       // Let the frontend know a tool is firing in the thoughts timeline
//       res.write(`event: thinking\ndata: ${JSON.stringify(`\n⚡ [Tool Firing]: Running ${toolName}...\n`)}\n\n`);

//       try {
//         // Dynamic tool resolver handles methods (POST/GET) and routing rules internally
//         toolResult = await executeDynamicTool(toolName, toolArgs);
//       } catch (error) {
//         toolResult = { success: false, error: `Tool execution failed: ${error.message}` };
//       }

//       messages.push({
//         role: 'tool',
//         tool_name: toolName,
//         content: JSON.stringify(toolResult)
//       });
//     }

//     // 5. Tail Recurse: Feed data variables directly back into the engine
//     return runAgentLoop(messages, res);
//   }
// }



// export async function runAgentLoop(messages, res) {
//     console.log(messages)
//   // Call your lower ollama wrapper
//   const responseStream = await sendToOllama(messages, toolRegistry);
//   let toolCalls = null;

//   for await (const chunk of responseStream) {
//     // 1. Immediately stream internal reasoning paths to the frontend
//     if (chunk.message.thinking) {
//       res.write(`event: thinking\ndata: ${JSON.stringify(chunk.message.thinking)}\n\n`);
//     } 
//     // 2. Stream base response content tokens
//     else if (chunk.message.content) {
//       res.write(`event: content\ndata: ${JSON.stringify(chunk.message.content)}\n\n`);
//     }

//     // 3. Keep records of tool intents if model emits them
//     if (chunk.message.tool_calls?.length) {
//       toolCalls = chunk.message.tool_calls;
//     }
//   }

//   // 4. Intercept Tool Call Execution Loops
//   if (toolCalls && toolCalls.length > 0) {
//     // Append assistant tool intent into state array
//     messages.push({ role: 'assistant', tool_calls: toolCalls });

//     for (const call of toolCalls) {
//       let toolResult = null;
      
//       // Let the frontend know a tool is firing in the thoughts timeline
//       res.write(`event: thinking\ndata: ${JSON.stringify(`\n⚡ [Tool Firing]: Running ${call.function.name}...\n`)}\n\n`);

//       if (call.function.name === 'get_current_weather') {
//         toolResult = await mockWeather(call.function.arguments.city);
//       } else if (call.function.name === 'get_clothing_advice') {
//         toolResult = await mockClothing(call.function.arguments.condition);
//       }

//       if (toolResult) {
//         messages.push({
//           role: 'tool',
//           tool_name: call.function.name,
//           content: JSON.stringify(toolResult)
//         });
//       }
//     }

//     // 5. Tail Recurse: Feed data variables directly back into the engine
//     return runAgentLoop(messages, res);
//   }
// }
